관리자의 예약 승인, 거절 기능 API
seat-checking/back-end pull request #130
Opened 2023-08-03 03:33 UTC by 0binn

## Summary
- Close #111 

<br>

## Changes 
- 예약 상태 변경 기능 구현
- Service, API를 User 쪽과 분리

<br>

## To Reviewers

<br>

2023-08-03 03:34 UTC, EllieHyun approved these changes

2023-08-03 03:42 UTC, benjaminuj reviewed
의견 남겼습니다

2023-08-03 03:42 UTC, benjaminuj commented on src/main/java/project/seatsence/src/reservation/service/AdminReservationService.java
> +    public void setReservationStatus(Long reservationId, ReservationStatus reservationStatus) {
이렇게 setter처럼 승인이나 거절 상태 값을 클라이언트에서 받아서 그때그때 받은 값 넣는것보다, 승인 API와 거절 API를 각각 만드는게 나을 것 같은데 어떠세요?

2023-08-03 03:46 UTC, 0binn commented on src/main/java/project/seatsence/src/reservation/service/AdminReservationService.java
> +    public void setReservationStatus(Long reservationId, ReservationStatus reservationStatus) {
두 방법 모두 크게 상관은 없을 것 같다고 느껴지는데 혹시 그렇게 생각하시는 이유가 있으실까요?!

2023-08-03 05:46 UTC, benjaminuj requested changes
수정했으면 하는 이유 남겼는데, 어떠신가요?

2023-08-03 05:46 UTC, benjaminuj commented on src/main/java/project/seatsence/src/reservation/api/AdminReservationApi.java
> +            @RequestBody ReservationStatus reservationStatus) {
아래 의견의 연장선인데, 정확히는 클라이언트에서 넘어오는 이 부분에서 파라미터로 받는걸 바꿨으면 좋겠다는 의견이었습니다!
클라이언트에서 값까지 상태로 받아버리면 우선 그 값을 해커가 다른걸로 변경할 수도 있을거라는 생각이 들어요. 두 번째로는 가장 큰 이유인데, 구현중이든 유지보수 시점이든 워딩이 변경됐을 때, 서버쪽 뿐만 아니라 클라이언트 코드도 바꿔야하는게 치명적인 단점같아요

2023-08-03 07:59 UTC, 0binn commented on src/main/java/project/seatsence/src/reservation/api/AdminReservationApi.java
> +            @RequestBody ReservationStatus reservationStatus) {
이해했습니다! 그럼 분리해서 반영하도록 하겠습니다.

2023-08-04 16:41 UTC, benjaminuj approved these changes
반영 감사합니다!

2023-08-05 02:53 UTC, merged