Store <> AdminInfo 통합에 따른 코드 변경사항 반영
seat-checking/back-end pull request #168
Opened 2023-08-10 16:25 UTC by EllieHyun

## Summary
- Close #166  

<br>

## Changes 
- Store <> AdminInfo 통합에 따른 코드 변경사항 반영

<br>

## To Reviewers
어쩔 수 없이 수정 범위가 큽니다🥲

<br>

2023-08-10 16:29 UTC, 0binn commented on src/main/java/project/seatsence/src/store/dao/StoreSpaceRepository.java
> +    List<StoreSpace> findAllByStore(Store tempStore);
파라미터명 수정 부탁드립니다!

2023-08-10 16:32 UTC, 0binn commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreResponse.java
> +    //    }
여기 주석 처리 하신건 일부러 남겨 놓으신걸까요??

2023-08-10 16:35 UTC, 0binn reviewed
코멘트 확인 부탁드려요!

2023-08-10 16:38 UTC, heyyjin requested changes
요청사항 남겼습니다!

2023-08-10 16:38 UTC, benjaminuj commented on src/main/java/project/seatsence/global/config/SwaggerConfig.java
> +        String jwtSchemeName = "JWT TOKEN";
여기 다 지우고 바꾸신 이유가뭘까요?

2023-08-10 16:38 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/domain/StoreChair.java
>      private String manageId;
이거 숫자만 받을 수 있게 수정 부탁드리겠습니다

2023-08-10 16:38 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/domain/StoreTable.java
> +    private String manageId;
테이블 관리 id 필요없는걸로 이야기되지 않았었나요?!

2023-08-10 16:41 UTC, benjaminuj commented on src/main/java/project/seatsence/global/config/SwaggerConfig.java
> +        String jwtSchemeName = "JWT TOKEN";
아 위에 코멘트 변경된거 지금 읽었습니다!
Swagger 인증인가쪽 제가 아직 진행중인데(이슈 진행중으로 되어있음), 저는 저거말고 다른 코드가 더 필요한걸로 알고있어요! 
혹시 저게 되는지 궁금하신거면, 우선 기존 코드는 전체 주석으로 변경 부탁드려도될까요?

2023-08-10 16:41 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreResponse.java
> +    //    }
앗 삭제해도 되는 코드입니다! 감사합니당

2023-08-10 16:41 UTC, EllieHyun commented on src/main/java/project/seatsence/global/config/SwaggerConfig.java
> +        String jwtSchemeName = "JWT TOKEN";
스웨거 JWT 토큰 설정이 안되더라구요..! 그래서 수정했습니다

2023-08-10 16:45 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/domain/StoreTable.java
> +    private String manageId;
아 넵 수정하겠습니다!

2023-08-10 16:45 UTC, benjaminuj requested changes

2023-08-10 16:45 UTC, benjaminuj commented on src/main/java/project/seatsence/global/config/SwaggerConfig.java
> +                                        .scheme("bearer")
B대문자, 맨 뒤에 " " 공백하나 있는게 저희 사용하고있는 규칙이라서 그렇게 수정부탁드리겠습니다!

2023-08-11 05:04 UTC, benjaminuj approved these changes
반영 감사합니다!

2023-08-11 06:22 UTC, 0binn approved these changes

2023-08-11 11:00 UTC, merged