feat: Separate StoreSpace API
seat-checking/back-end pull request #194
Opened 2023-08-14 16:31 UTC by EllieHyun

## Summary
- close #174 

<br>

## Changes 
- 관리자 스페이스 조회 API 가게별로 분리
- 스페이스 별 좌석 조회
- 가게 스페이스 추가
- 관리자 소유 가게 추가 정보 응답

<br>

## To Reviewers
-

2023-08-14 17:13 UTC, heyyjin requested changes
의견남겼습니당!

2023-08-14 17:13 UTC, heyyjin commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +            description = "idOpenNow : 영업 중 여부, isCloseToday : 휴업 여부")
description에 오타가 있는 것 같은데, 확인 부탁드리겠습니다!

2023-08-14 17:13 UTC, heyyjin commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceSeatResponse.java
> +@Setter
혹시 모든 필드에 Setter가 필요해서 사용하신걸까요?!

2023-08-14 17:13 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +    @Operation(summary = "admin 가게 기본 정보 등록하기", description = "가게의 카테고리 - 음식점, 카페, 모임, 기타 중 선택")
저희 가게 카테고리 '기타'없어졌는데, 확인부탁드려요! 추가로 '기타'관련한 코드있으면 , 그 부분도 수정부탁드리겠습니다!

2023-08-15 00:46 UTC, 0binn approved these changes

2023-08-15 06:52 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +            description = "idOpenNow : 영업 중 여부, isCloseToday : 휴업 여부")
오타 수정하였습니다! 발견 감사합니다!

2023-08-15 06:53 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceSeatResponse.java
> +@Setter
이전에 만들어둔 것 같아요! setter 삭제하겠습니다

2023-08-15 06:53 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +    @Operation(summary = "admin 가게 기본 정보 등록하기", description = "가게의 카테고리 - 음식점, 카페, 모임, 기타 중 선택")
기타 카테고리는 코드에서 삭제했습니다!

2023-08-15 06:58 UTC, benjaminuj approved these changes
반영감사합니다!

2023-08-15 06:58 UTC, merged