fix: update store space field name and reservation unit format
seat-checking/back-end pull request #213
Opened 2023-08-20 08:42 UTC by EllieHyun

## Summary
- Close #212 

<br>

## Changes 
- https://www.notion.so/mansu31/d2d0f064abf4491a965ca277bb48ad45?pvs=4 위 문서 참고하여 필드 이름 변경, 응답 형태 수정 등 요구사항 반영하였습니다!

<br>

## To Reviewers

<br>

2023-08-20 09:00 UTC, 0binn approved these changes

2023-08-20 09:08 UTC, benjaminuj requested changes
몇가지 요청사항 남겼는데, 관련한 코드 수정 부탁드리겠습니다!!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceChairRequest.java
> +    @NotBlank private String i;
i 가 뭔가요? 진짜 그냥 'i'라면 어떤건지 옆에 주석 부탁드릴게요!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceTableRequest.java
> +    @NotBlank private String i;
여기도 i 주석 부탁드리겠습니다!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceTableRequest.java
> +    @PositiveOrZero private int w;
혹시 이거 'width','height'면 풀네임으로 수정 부탁드려도 될까요?

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/request/ReservationUnitRequest.java
> +    private Boolean seat;
저희 용어 관계가 'seat = chair + table + space'라서 의자 단위면 chair로 수정 부탁드리겠습니다!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceChairResponse.java
> +    private String i;
이것도 i 뭔지 주석 부탁드릴게요!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/response/AdminStoreSpaceTableResponse.java
> +    private int w;
저희 이야기 나눴던대로, 약어 사용 지양부탁드리겠습니다!

2023-08-20 09:08 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/dto/response/ReservationUnitResponse.java
> +    private Boolean seat;
여기도 chair로 수정 부탁드려용 ㅎㅎ

2023-08-20 09:11 UTC, sonmansu commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceChairRequest.java
> +    @NotBlank private String i;
프론트단에서 아이템 식별에 사용되는 key라고 적으면 될 것 같아요

2023-08-20 09:13 UTC, sonmansu commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceTableRequest.java
> +    @PositiveOrZero private int w;
이거 제가 수정 부탁드린건데 w, h, x, y 로 오면 프론트에서 데이터 읽고 보낼 때 매번 전처리안해줘도 돼서 부탁드렸어요! 약어로 보내주시면 훨씬 편할 것 같아요

2023-08-20 09:17 UTC, sonmansu commented on src/main/java/project/seatsence/src/store/dto/request/AdminStoreSpaceTableRequest.java
> +    @PositiveOrZero private int w;
약어 사용이 안된다면 이런 식으로 데이터 전달할 때 변수명을 바꿔서 보내주실 수 있으신가요? https://lemontia.tistory.com/905

2023-08-21 16:43 UTC, benjaminuj approved these changes
반영 감사합니다!

2023-08-22 00:51 UTC, merged