feat: Get Admin Store Form
seat-checking/back-end pull request #55
Opened 2023-07-01 07:32 UTC by EllieHyun

## Summary
- close #40 

<br>

## Changes 
- 관리자가 자신의 가게 형태를 조회합니다

<br>

2023-07-01 08:07 UTC, benjaminuj requested changes
의견 남겼습니다!

2023-07-01 08:07 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
>      @PatchMapping("/{id}")
REST 규칙을 지키기위해서, id값을 명확히 명시해주면 좋을 것 같습니다. 가게를 수정하는거라면 `{store-id}` 이런식으로요!

2023-07-01 10:33 UTC, 0binn approved these changes
확인했습니다. 전체적으로 id값 명시만 부탁드릴게요!

2023-07-03 04:31 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
>      @PatchMapping("/{id}")
반영해두었습니다!

2023-07-03 06:46 UTC, benjaminuj requested changes
uri 표기법 수정 부탁드려요

2023-07-03 06:46 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +    @GetMapping("/{storeId}")
저희 규칙으로 uri 여러 명사가 합쳐질 경우 '-'로 구분하기로했었는데 관련 Id값들이 카멜표기법으로 되어있네요! 확인부탁드리겠습니다

2023-07-03 07:05 UTC, benjaminuj approved these changes
👍🏻 고생하셨습니다!

2023-07-03 07:06 UTC, merged