관리자 새로운 가게 등록시 StoreMember(OWNER) 추가
seat-checking/back-end pull request #93
Opened 2023-07-23 07:35 UTC by EllieHyun

## Summary
- close #87 

<br>

## Changes 
- 관리자가 새로운 가게 등록시 StoreMember(OWNER)추가
- jwt claim을 통해 요청 유저 정보 가져오기

<br>

## To Reviewers
- 로직 수정하면서 test가 깨져서 User, StoreMember Entity Protected Level 삭제했습니다!
- adaptor 관련 질문 주신거 디코에 답변 달아놨어요! @benjaminuj 

<br>

2023-07-23 15:16 UTC, benjaminuj requested changes

2023-07-23 15:16 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +                Jwts.parserBuilder()
해당 코드는 JwtProvider의 private Jws<Claims> parse(String token) 메소드에서 제공하고있는데, 이 부분 끌어쓰는건 어떠세요? 
그런데 StoreService에서 JwtProvider로 연결하는것보다 adminStore쪽이니 이렇게 따로 사용하는게 더 좋을것같기도하고,, 어떻게하는게 좋을까요?

2023-07-23 15:16 UTC, benjaminuj commented on src/main/java/project/seatsence/src/store/domain/StoreMember.java
>  @Setter
Setter 어노테이션은 위험하니 사용하지말고, 필요한 필드만 직접 setter생성해서 사용하도록 수정가능할까요?

2023-07-23 16:50 UTC, 0binn approved these changes

2023-07-24 02:27 UTC, EllieHyun commented on src/main/java/project/seatsence/src/store/api/AdminStoreApi.java
> +                Jwts.parserBuilder()
아 jwtProvider에 있는거 사용해도 될 것 같아요! 수정하겠습니당

2023-07-24 06:02 UTC, benjaminuj approved these changes

2023-07-24 06:02 UTC, merged